### ISSUE TITLE
Consumer trying to write on already closed connection

### ISSUE THREAD

**Issue by rlavolee** [hnaderi/lepus#234]
Hi,

I've come accross a strange behavior with Lepus 0.5.0. Sometimes I find a consumer crashing because it's trying to write on already closed connection.

```
Caused by: lepus.client.internal.OutputWriter$ConnectionIsClosed$: Connection is already closed!
```

Here's the full stacktrace.

```
at fs2.CompositeFailure$.fromResults(CompositeFailure.scala:88)
2024-03-11T09:19:00+01:00 at scala.util.Either.fold(Either.scala:190)
2024-03-11T09:19:00+01:00 at fs2.CompositeFailure$.fromResults$$anonfun$1(CompositeFailure.scala:88)
2024-03-11T09:19:00+01:00 at fs2.Stream$$anon$2.applyOrElse(Stream.scala:1963)
2024-03-11T09:19:00+01:00 fs2.CompositeFailure: Multiple exceptions were thrown (2), first lepus.client.internal.OutputWriter$ConnectionIsClosed$: Connection is already closed!
2024-03-11T09:19:00+01:00 at fs2.CompositeFailure$.apply(CompositeFailure.scala:45)
2024-03-11T09:19:00+01:00 at fs2.CompositeFailure$.apply(CompositeFailure.scala:58)
2024-03-11T09:19:00+01:00 at flatMap @ fs2.Pull$.fs2$Pull$$$_$interruptGuard$1(Pull.scala:961)
2024-03-11T09:19:00+01:00 at get @ fs2.concurrent.SignallingRef$$anon$4.getAndDiscreteUpdatesImpl(Signal.scala:292)
2024-03-11T09:19:00+01:00 at fs2.Stream$$anon$2.applyOrElse(Stream.scala:1964)
2024-03-11T09:19:00+01:00 at flatMap @ fs2.Compiler$Target.flatMap(Compiler.scala:163)
2024-03-11T09:19:00+01:00 at flatMap @ fs2.Compiler$Target.flatMap(Compiler.scala:163)
2024-03-11T09:19:00+01:00 at get @ fs2.concurrent.SignallingRef$$anon$4.getAndDiscreteUpdatesImpl(Signal.scala:292)
2024-03-11T09:19:00+01:00 at flatMap @ fs2.Compiler$Target.flatMap(Compiler.scala:163)
2024-03-11T09:19:00+01:00 at flatMap @ fs2.Compiler$Target.flatMap(Compiler.scala:163)
2024-03-11T09:19:00+01:00 at flatMap @ fs2.Compiler$Target.flatMap(Compiler.scala:163)
2024-03-11T09:19:00+01:00 at get @ fs2.concurrent.SignallingRef$$anon$4.getAndDiscreteUpdatesImpl(Signal.scala:292)
2024-03-11T09:19:00+01:00 at flatMap @ fs2.Pull$.fs2$Pull$$$_$interruptGuard$1(Pull.scala:961)
2024-03-11T09:19:00+01:00 at fs2.Stream.onFinalizeCase$$anonfun$1(Stream.scala:2142)
2024-03-11T09:19:00+01:00 at lepus.client.internal.ConnectionState.onClosed$(ConnectionState.scala:33)
2024-03-11T09:19:00+01:00 at lepus.client.internal.ConnectionState$$anon$1.onClosed(ConnectionState.scala:59)
2024-03-11T09:19:00+01:00 at flatMap @ fs2.Compiler$Target.flatMap(Compiler.scala:163)
2024-03-11T09:19:00+01:00 at flatMap @ fs2.Compiler$Target.flatMap(Compiler.scala:163)
2024-03-11T09:19:00+01:00 at flatMap @ fs2.Pull$.fs2$Pull$$$_$interruptGuard$1(Pull.scala:961)
2024-03-11T09:19:00+01:00 at flatMap @ fs2.Pull$.fs2$Pull$$$_$interruptGuard$1(Pull.scala:961)
2024-03-11T09:19:00+01:00 at get @ fs2.concurrent.SignallingRef$$anon$4.getAndDiscreteUpdatesImpl(Signal.scala:292)
2024-03-11T09:19:00+01:00 at lepus.client.internal.ConnectionState$$anon$1.onFailed(ConnectionState.scala:93)
2024-03-11T09:19:00+01:00 at lepus.client.internal.OutputWriter$ConnectionIsClosed$.<clinit>(OutputWriter.scala:49)
2024-03-11T09:19:00+01:00 at flatMap @ fs2.Compiler$Target.flatMap(Compiler.scala:163)
2024-03-11T09:19:00+01:00 at lepus.client.internal.ConnectionState.onClosed(ConnectionState.scala:37)
2024-03-11T09:19:00+01:00 Caused by: lepus.client.internal.OutputWriter$ConnectionIsClosed$: Connection is already closed!
2024-03-11T09:19:00+01:00 at lepus.client.Connection$.receive$$anonfun$1$$anonfun$2(Connection.scala:118)
2024-03-11T09:19:00+01:00 at lepus.client.internal.OutputWriter$$anon$1.onClose(OutputWriter.scala:44)
2024-03-11T09:19:00+01:00 at flatMap @ fs2.Compiler$Target.flatMap(Compiler.scala:163)
2024-03-11T09:19:00+01:00 at flatMap @ fs2.Compiler$Target.flatMap(Compiler.scala:163)
2024-03-11T09:19:00+01:00 at map @ fs2.concurrent.SignallingRef$$anon$4.get(Signal.scala:257)
2024-03-11T09:19:00+01:00 at fs2.concurrent.SignallingRef$$anon$4.modify$$anonfun$1(Signal.scala:302)
2024-03-11T09:19:00+01:00 at fs2.concurrent.SignallingRef$.fs2$concurrent$SignallingRef$$$_$updateAndNotify$1(Signal.scala:246)
2024-03-11T09:19:00+01:00 at fs2.Stream$NestedStreamOps$.stop$12$$anonfun$1$$anonfun$2(Stream.scala:4250)
2024-03-11T09:19:00+01:00 at fs2.CompositeFailure$.apply(CompositeFailure.scala:45)
2024-03-11T09:19:00+01:00 fs2.CompositeFailure: Multiple exceptions were thrown (2), first lepus.client.internal.OutputWriter$ConnectionIsClosed$: Connection is already closed!
2024-03-11T09:19:00+01:00 at use @ fs2.Compiler$Target.compile(Compiler.scala:158)
2024-03-11T09:19:00+01:00 at modify @ fs2.internal.Scope.close(Scope.scala:262)
2024-03-11T09:19:00+01:00 at flatMap @ lepus.client.internal.OutputWriter$$anon$1.write(OutputWriter.scala:41)
2024-03-11T09:19:00+01:00 at tryGet @ lepus.client.internal.OutputWriter$$anon$1.write(OutputWriter.scala:37)
2024-03-11T09:19:00+01:00 at flatMap @ fs2.Compiler$Target.flatMap(Compiler.scala:163)
2024-03-11T09:19:00+01:00 at fs2.concurrent.SignallingRef$.fs2$concurrent$SignallingRef$$anon$4$$_$update$$anonfun$1(Signal.scala:299)
2024-03-11T09:19:00+01:00 at fs2.Stream$NestedStreamOps$.stop$12$$anonfun$1(Stream.scala:4250)
2024-03-11T09:19:00+01:00 at scala.Option.fold(Option.scala:263)
2024-03-11T09:19:00+01:00 at fs2.CompositeFailure$.apply(CompositeFailure.scala:58)
2024-03-11T09:19:00+01:00 at flatMap @ fs2.Compiler$Target.flatMap(Compiler.scala:163)
2024-03-11T09:19:00+01:00 at flatMap @ fs2.Compiler$Target.flatMap(Compiler.scala:163)
2024-03-11T09:19:00+01:00 at flatMap @ fs2.Compiler$Target.flatMap(Compiler.scala:163)
2024-03-11T09:19:00+01:00 at flatMap @ fs2.Stream$NestedStreamOps$.signalResult$1(Stream.scala:4344)
2024-03-11T09:19:00+01:00 at get @ fs2.concurrent.SignallingRef$$anon$4.getAndDiscreteUpdatesImpl(Signal.scala:292)
2024-03-11T09:19:00+01:00 at acquire @ fs2.Stream.run$1$$anonfun$1(Stream.scala:1974)
2024-03-11T09:19:00+01:00 at apply @ lepus.client.StartupNegotiation$.apply(StartupNegotiation.scala:45)
2024-03-11T09:19:00+01:00 at flatMap @ fs2.Compiler$Target.flatMap(Compiler.scala:163)
2024-03-11T09:19:00+01:00 at fs2.internal.Scope.$anonfun$2$$anonfun$1(Scope.scala:192)
2024-03-11T09:19:00+01:00 at fs2.Pull$.$anonfun$2(Pull.scala:1105)
2024-03-11T09:19:01+01:00 at fs2.internal.Scope.$anonfun$2$$anonfun$1(Scope.scala:192)
2024-03-11T09:19:01+01:00 at lepus.client.internal.ConnectionState.onClosed$(ConnectionState.scala:33)
2024-03-11T09:19:01+01:00 at tryGet @ lepus.client.internal.OutputWriter$$anon$1.write(OutputWriter.scala:37)
2024-03-11T09:19:01+01:00 at fs2.Stream.onFinalizeCase$$anonfun$1(Stream.scala:2142)
2024-03-11T09:19:01+01:00 at flatMap @ fs2.Compiler$Target.flatMap(Compiler.scala:163)
2024-03-11T09:19:01+01:00 at modify @ fs2.internal.Scope.close(Scope.scala:262)
2024-03-11T09:19:01+01:00 at lepus.client.internal.ConnectionState$$anon$1.onClosed(ConnectionState.scala:59)
2024-03-11T09:19:01+01:00 at lepus.client.internal.ConnectionState.onClosed(ConnectionState.scala:37)
2024-03-11T09:19:01+01:00 at lepus.client.internal.ConnectionState$$anon$1.onFailed(ConnectionState.scala:93)
2024-03-11T09:19:01+01:00 Caused by: lepus.client.internal.OutputWriter$ConnectionIsClosed$: Connection is already closed!
2024-03-11T09:19:01+01:00 at flatMap @ fs2.Pull$.goCloseScope$1$$anonfun$1$$anonfun$3(Pull.scala:1217)
2024-03-11T09:19:01+01:00 at get @ fs2.concurrent.SignallingRef$$anon$4.getAndDiscreteUpdatesImpl(Signal.scala:292)
2024-03-11T09:19:01+01:00 at flatMap @ lepus.client.internal.OutputWriter$$anon$1.write(OutputWriter.scala:41)
2024-03-11T09:19:01+01:00 at fs2.Pull$.$anonfun$2(Pull.scala:1105)
2024-03-11T09:19:01+01:00 at lepus.client.Connection$.receive$$anonfun$1$$anonfun$2(Connection.scala:118)
2024-03-11T09:19:01+01:00 at flatMap @ fs2.Compiler$Target.flatMap(Compiler.scala:163)
2024-03-11T09:19:01+01:00 at as @ fs2.Stream.merge$$anonfun$1$$anonfun$1$$anonfun$1(Stream.scala:1956)
2024-03-11T09:19:01+01:00 at rethrow$extension @ fs2.Compiler$Target.compile$$anonfun$1(Compiler.scala:157)
2024-03-11T09:19:01+01:00 at flatMap @ fs2.Compiler$Target.flatMap(Compiler.scala:163)
2024-03-11T09:19:01+01:00 at modify @ fs2.internal.Scope.close(Scope.scala:262)
2024-03-11T09:19:01+01:00 at lepus.client.internal.OutputWriter$$anon$1.onClose(OutputWriter.scala:44)
2024-03-11T09:19:01+01:00 at lepus.client.internal.OutputWriter$ConnectionIsClosed$.<clinit>(OutputWriter.scala:49)
2024-03-11T09:19:01+01:00 at use @ fs2.Compiler$Target.compile(Compiler.scala:158)
2024-03-11T09:19:01+01:00 at acquire @ fs2.Stream.run$1$$anonfun$1(Stream.scala:1974)
2024-03-11T09:19:01+01:00 at apply @ lepus.client.StartupNegotiation$.apply(StartupNegotiation.scala:45)
```

What do you think about it?

**Comment by hnaderi** [comment]
Hi @rlavolee,
In what scenarios does this error happen? Can you also check and share the server log?
This can happen if the connection is closed by the server (i.e. client receives a `ConnectionClose` command from the server)
It might also be due to resource/stream lifecycle management.

**Comment by hnaderi** [comment]
Can you also reproduce this problem with debug log on? It can help to detect the problem faster by having the communication log between client and server.

**Comment by rlavolee** [comment]
Unfortunately it happens sporadically with the same consumer. It worked well 4 days straight and then crashed.
I haven't yet found a particular pattern to reproduce the problem. I'll try to get more logs.

**Comment by gnoireaux** [comment]
Hi @hnaderi ,
I applaud your willingness to search for the cause of the closing of the connection. Indeed, if the connection should not have been closed: it would be useful to prevent the closing.
However, there are many reasons why the connections would close. And some of the closures are unavoidable. Therefore, we would like to know how to implement checking the state of the connection before using it. (If it is what would prevent the consumer from crashing.)
We thank you for pointers ! (@rlavolee and I are colleagues.)

**Comment by hnaderi** [comment]
Hi @gnoireaux,
In order to monitor for channel or connection status, you can use the `Connection#status` and `Channel#status`, which are instances of `Signal` from fs2.
For example:
```scala
val whenClosed = connection.status.map(_ == Status.Closed)
...
consumer.interruptWhen(whenClosed)
```

**Comment by rlavolee** [comment]
Hi @hnaderi ! I'm gonna close this issue since I can't reproduce it outside of my environnement. Logs point to frame decoding errors so I guess there is a proxy messing with frames. Thank you for your help anyway :)

**Comment by hnaderi** [comment]
> Hi @hnaderi, is it possible to do some re-connection automatically if we lost it ? If you show me where I can try to produce a PR.

Hi @guillaumebadin, yes it is.
It depends on how you want to handle that case, there are no general ways that work for everyone, so it's better left to be a user-land decision instead of being in the library itself, like how it's done in skunk for example. It can however be implemented in a utility library or maybe the std lib.
For implementing channel/connection automatic recovery, one must keep track of the channel/connection state changes (i.e. `channel.status`) and redo everything on a new connection/channel when it gets a closed state.
It's also possible to create an adapter like connection/channel that does all these stuff seamlessly. This might however need extra care when handling server close commands, otherwise it might lead to a positive feedback loop.
